service: opensearch-training
frameworkVersion: "3"

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - es:ES*
          Resource: 
            - arn:aws:es:ap-northeast-1:744743450114:domain/opensearch-test-dev
  vpc:
    subnetIds:
      - subnet-0afc01b6d960c28c2
      - subnet-0a52d9316f1ae12d1
    securityGroupIds:
      - sg-0a5b75994c08c8410

functions:
  searchCalls:
    handler: handler.searchCalls
    events:
      - http:
          path: /api/v1/calls
          method: GET
  addCallDocument:
    handler: handler.addCallDocument
    events:
      - http:
          path: /api/v1/calls
          method: POST